Repository looker-open-source/sdk-codegen, pull requests merged in 2021-02, with the labels that each got.

#474 Upgraded openapi-generator-cli for axios security issue
  packages/sdk-codegen-scripts/package.json
  packages/sdk-codegen-scripts/src/legacyGenerator.ts
  yarn.lock
Labels: dependencies

#475 Minor improvements to some SDK readmes
  docs/cors.md
  kotlin/README.md
  packages/sdk-node/README.md
  packages/sdk/README.md
  swift/looker/README.md
Labels: documentation

#486 chore: release
  .release-please-manifest.json
  packages/sdk-codegen/CHANGELOG.md
  packages/sdk-codegen/package.json
  python/CHANGELOG.md
  python/looker_sdk/version.py
Labels: autorelease: pending
