Repository looker-open-source/sdk-codegen, pull requests merged in 2021-03, with the labels that each got.

#510 chore: release
  .release-please-manifest.json
  packages/api-explorer/CHANGELOG.md
  packages/api-explorer/package.json
  packages/extension-api-explorer/CHANGELOG.md
  packages/extension-api-explorer/package.json
  packages/extension-sdk-react/CHANGELOG.md
  packages/extension-sdk-react/package.json
  packages/extension-sdk/CHANGELOG.md
  packages/extension-sdk/package.json
  packages/run-it/CHANGELOG.md
  packages/run-it/package.json
  packages/sdk-codegen-scripts/CHANGELOG.md
  packages/sdk-codegen-scripts/package.json
  packages/sdk-codegen/CHANGELOG.md
  packages/sdk-codegen/package.json
  packages/sdk-node/CHANGELOG.md
  packages/sdk-node/package.json
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  python/CHANGELOG.md
  python/looker_sdk/version.py
Labels: autorelease: pending

#537 chore: release
  .release-please-manifest.json
  CHANGELOG.md
  package.json
  packages/api-explorer/CHANGELOG.md
  packages/api-explorer/package.json
  packages/extension-api-explorer/CHANGELOG.md
  packages/extension-api-explorer/package.json
  packages/extension-sdk-react/CHANGELOG.md
  packages/extension-sdk-react/package.json
  packages/extension-sdk/CHANGELOG.md
  packages/extension-sdk/package.json
  packages/hackathon/CHANGELOG.md
  packages/hackathon/package.json
  packages/run-it/CHANGELOG.md
  packages/run-it/package.json
  packages/sdk-codegen-scripts/CHANGELOG.md
  packages/sdk-codegen-scripts/package.json
  packages/sdk-codegen/CHANGELOG.md
  packages/sdk-codegen/package.json
  packages/sdk-node/CHANGELOG.md
  packages/sdk-node/package.json
  packages/sdk-rtl/CHANGELOG.md
  packages/sdk-rtl/package.json
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/wholly-sheet/CHANGELOG.md
  packages/wholly-sheet/package.json
Labels: CI:HOLD, autorelease: pending

#540 fix: legacy generator was broken
  packages/sdk-codegen-scripts/src/fetchSpec.ts
  packages/sdk-codegen-scripts/src/legacyGenerator.ts
  packages/sdk-codegen/src/codeGenerators.ts
Labels: bug
